## ALACRITTY CONFIGURATION
# by josh (2024)
#

import = [
  "~/.config/alacritty/themes/tokyo-night.toml" # change path to change the theme
]

# Window
[window]
opacity = 1.0
padding = { x = 5, y = 5 }
dynamic_padding  = true
decorations = "Full"
title = "Terminal"
dynamic_title = false
decorations_theme_variant = "Dark"
#
# Scrolling
[scrolling]
history = 100000
multiplier = 3
#
## Font
[font]
normal = { family = "consolas", style = "Bold" }
italic = { family = "consolas", style = "Bold Italic" }
